config/routes.rb
Rails.application.routes.draw do

  root to: "users#new" 

  get '/signup' => 'users#new'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  # get '/<%= current_user.username %>'


  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
	include ActiveModel::SecurePassword

	has_secure_password

	validates :username, presence: true
	validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
	validates :password, confirmation: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	if session[:user_id]
  		@current_user ||= User.find(session[:user_id])
  	end
  end
  helper_method :current_user

  def authorize
  	redirect_to login_path unless current_user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:user][:email])

		if user && user.authenticate(params[:user][:password])
			flash[:success] = "Logged in successfully"
			session[:user_id] = user.id
			redirect_to users_path
		else
			flash.now[:danger] = "Email or password is incorrect"
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to '/login'
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authorize

	def index 
		# @users = current_user.users
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		user = User.find_by(email: params[:user][:email])
		@user = User.new(params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation))
		
		if @user.valid? 
				@user.save
				flash[:info] = "Signed up successfully"
				redirect_to users_path
		else
			flash.now[:danger] = @user.errors.full_messages.to_sentence
			render :new
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoSkate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
	<body>

		<nav class="navbar navbar-default">
			<h2>Go skate</h2>
			<% if current_user %>
				<!-- <%= current_user.username %> -->
				<%= link_to "Log out", logout_path, class: 'btn btn-default' %>
			<% end %>
		</nav>

		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>" role="alert">
				<%= value %>
			</div>
		<% end %>

	<%= yield %>

	</body>
</html>

app/views/users/new.html.erb
	<!-- SIGN UP PAGE -->


<div class="signup col-md-2">
	
	<!-- SIGN UP and LOG IN tabs -->
	<ul class="nav nav-tabs">
		<li class="active">
			<%= link_to("Sign up", signup_path) %>
		</li>
		<li>
			<%= link_to("Log In", login_path) %>
		</li>
	</ul>

	<br>

	<%= form_for @user do |f| %>
		<form class="form-group">
	
		<strong>First name</strong> <br>
			<%= f.text_field :first_name, class: "form-control" %> <br>
		<strong>Last name</strong> <br>
			<%= f.text_field :last_name, class: "form-control" %> <br>
		<strong>Username</strong> <br>
			<%= f.text_field :username, class: "form-control" %> <br>
		<strong>E-mail</strong> <br>
			<%= f.text_field :email, class: "form-control" %> <br>
		<strong>Password</strong> <br>
			<%= f.password_field :password, class: "form-control" %> <br>
		<strong>Confirm password</strong> <br>
			<%= f.password_field :password_confirmation, class: "form-control" %> <br>
			<%= f.submit "Go skate!", class: "btn btn-default center-block" %>

		</form>
	<% end %>
</div>